### ISSUE TITLE
你好作者，我也下载的《宿命之环》，遇到问题了

### ISSUE THREAD

**Issue by hezhongfeng** [freeok/so-novel#11]
我是 macos，运行的 app.jar
结果html都是这种：
<img width="1232" alt="image" src="https://github.com/freeok/so-novel/assets/12163050/d90b76ae-bca8-45ff-b26a-b0e5ee5d3b31">
生成的epub也都是黑的，也不完整：
<img width="1054" alt="image" src="https://github.com/freeok/so-novel/assets/12163050/7561a41b-d5f3-41ec-8663-af8c5f033618">

**Comment by freeok** [comment]
你好，这是源站的问题，建议隔段时间重新下载。目前仅维护一个书源，后面会陆续新增

**Comment by freeok** [comment]
https://github.com/freeok/so-novel/releases/tag/v1.5.8

**Comment by hezhongfeng** [comment]
好的，感谢

**Comment by hezhongfeng** [comment]
试了下，样式问题解决了，体验很好，直接运行 app.jar 即可
