### ISSUE TITLE
v1.5.8 release issue

### ISSUE THREAD

**Issue by ownia** [freeok/so-novel#12]
For the v1.5.8 release (https://github.com/freeok/so-novel/releases/tag/v1.5.8), it looks like the version number is still 1.5.7. Refer to `pom.xml` and `MANIFEST.MF`. It might direct to a corrupted commit (https://github.com/freeok/so-novel/commit/e6c0ccb33496c9f4a7ab53e05adf39de00c2ab90).

**Comment by freeok** [comment]
re released
