### ISSUE TITLE
推荐书源 www.69shuba.pro

### ISSUE THREAD

**Issue by Zero-114** [freeok/so-novel#13]
佬这个网站感觉书的内容都挺全，www.69shuba.pro。是否可以添加一个，缺点就是必须开梯子才能打开这个网站。

**Comment by Zero-114** [comment]
这个网站小说有资源的书内容都挺好，更新也多，我用其他插件下载老是会跳段不知道为什么。

**Comment by freeok** [comment]
书源最好是能直接访问的

**Comment by freeok** [comment]
v1.7.3 已支持
