### ISSUE TITLE
推荐书源发到此处

### ISSUE THREAD

**Issue by freeok** [freeok/so-novel#15]
https://www.xbiqugu.com/

**Comment by freeok** [comment]
仅接收优质书源，尽量满足以下条件：
1. [起点人气榜单](https://www.qidian.com/rank/)的书能搜到
2. 书库全
3. 新书热书能同步更新
4. 错别字少、广告少
5. 无限流
6. 国内可直接访问

**Comment by zchentest** [comment]
> https://www.xbiqugu.com/

请问完本神站可以吗，有比较小众的书

https://www.xwbsz.com/rank/

**Comment by zchentest** [comment]
> > https://www.xbiqugu.com/
> 
> 请问完本神站可以吗，有比较小众的书
> 
> https://www.xwbsz.com/rank/

我试了下搜索不可用，直接输入链接是可以的
需去掉过滤
ChapterFilter.filter
然后不知道是否是网络问题，我这边需要增加重试，否则一千章节中会存在约二十几个章节网页超时

总之勉强可用了   谢谢大佬

**Comment by zchentest** [comment]
> > > https://www.xbiqugu.com/
> > 
> > 
> > 请问完本神站可以吗，有比较小众的书
> > https://www.xwbsz.com/rank/
> 
> 我试了下搜索不可用，直接输入链接是可以的 需去掉过滤 ChapterFilter.filter 然后不知道是否是网络问题，我这边需要增加重试，否则一千章节中会存在约二十几个章节网页超时
> 
> 总之勉强可用了 谢谢大佬

当标题存在""时，合并epub时 出现问题(文件名、目录名或卷标语法不正确。)

**Comment by freeok** [comment]
忘记说明先决条件了，无法搜索的书源是肯定不可以的。
等下会写专门提书源的 issue template
