### ISSUE TITLE
现在这个书源无法访问了

### ISSUE THREAD

**Issue by 1chuci** [freeok/so-novel#25]

**Comment by freeok** [comment]
![image](https://github.com/user-attachments/assets/22daf4fa-98ac-4717-a6d0-979c3c451f5f)

**Comment by 1chuci** [comment]
> ![image](https://private-user-images.githubusercontent.com/51998152/357443429-22daf4fa-98ac-4717-a6d0-979c3c451f5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTg1OTIsIm5iZiI6MTcyMzU1ODI5MiwicGF0aCI6Ii81MTk5ODE1Mi8zNTc0NDM0MjktMjJkYWY0ZmEtOThhYy00NzE3LWE2ZDAtOTc5YzNjNDUxZjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDE0MTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMjg1ZDI2ZGMxOWNhYzRhOGEwMjY2NzI3MjM3YjYyZWE3YjZkNWM5M2M3ZmZmNzRjMzY1MDdhMjVlZWY1OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1TqRtDi9zN53m4lxbxQu7EVblqXU_J7s7hppfmALgR0)

![屏幕截图 2024-08-13 221544](https://github.com/user-attachments/assets/73b94046-3090-4bc1-b9c9-28cc3092bca4)
大佬请问这个是什么问题

**Comment by freeok** [comment]
网络问题吧，另外最新版是 v1.5.9

**Comment by 1chuci** [comment]
> 网络问题吧，另外最新版是 v1.5.9

已经更新，能访问这个网站，但是还是没法搜

**Comment by freeok** [comment]
```bash
nslookup www.xbiqugu.net
```
看下你的执行结果

**Comment by 1chuci** [comment]
![1](https://github.com/user-attachments/assets/5460d030-64b9-4076-90b7-cac9da9676ae)
![2](https://github.com/user-attachments/assets/3004e98e-d6d2-4cf1-ab67-7cc6c4c01047)
![3](https://github.com/user-attachments/assets/6b9eef21-d666-4000-ac71-2b442e9c6e73)
似乎是我的DNS配置有问题

**Comment by freeok** [comment]
是的，用阿里DNS吧
https://alidns.com/

**Comment by 1chuci** [comment]
> 是的，用阿里DNS吧 https://alidns.com/

解决了，感谢！！
