### ISSUE TITLE
关于其他阅读软件兼容性问题

### ISSUE THREAD

**Issue by wintopic** [freeok/so-novel#32]
感谢大佬的软件，很好用！有一个小疑惑，koodo-reader可以正确打开，但是WPS不能，不知道为什么ToT
![image](https://github.com/user-attachments/assets/37897ea2-1e93-47ef-ab6a-ce8cbde72a38)

**Comment by freeok** [comment]
wps 版本？

**Comment by aslbdf** [comment]
你好，但是掌阅APP也无法正确打开生成的EPUB文件

**Comment by freeok** [comment]
> 你好，但是掌阅APP也无法正确打开生成的EPUB文件

3 选 1 
1. 下载 txt 格式，见 https://github.com/freeok/so-novel/issues/147
2. 用 [Calibre](https://calibre-ebook.com/zh_CN) 修复
3. 更换 [Readest](https://readest.com/) 阅读器

**Comment by bigxixi** [comment]
做了一个在线修复工具，可以试试
https://bigxixi.com/soNovelEpubFixer/index.html
