### ISSUE TITLE
推荐书源 [https://www.shuhaige.net/]

### ISSUE THREAD

**Issue by FemalePresident** [freeok/so-novel#33]
### 确定推荐的书源满足上述条件？

- [x] #34

### 书源 URL

https://www.shuhaige.net/

### 书源类型

网络小说

### 勾选满足的条件（满足 3 个及以上为优质书源）

- [ ] 无限流
- [x] 书库全
- [X] 起点人气榜单的书能搜到（https://www.qidian.com/rank）
- [X] 新书热书能同步更新
- [X] 正文错别字少

### 推荐理由

你好 能否支持自定义书源？这个网站的质量比较不错

**Comment by freeok** [comment]
后面尝试适配

**Comment by freeok** [comment]
适配成功，预计下个版本发布

**Comment by FemalePresident** [comment]
谢谢

**Comment by luozidd** [comment]
你别说这个网站大部分小说的都有！

**Comment by xiongaox** [comment]
为什么搜不到《[都重生了谁考公务员啊](https://www.qidian.com/book/1038504669/)》这本书？不过这个书源可以搜得到番茄的，还算不错，脚本自带的那个搜不到番茄的

**Comment by freeok** [comment]
> 为什么搜不到《[都重生了谁考公务员啊](https://www.qidian.com/book/1038504669/)》这本书？不过这个书源可以搜得到番茄的，还算不错，脚本自带的那个搜不到番茄的

在此推荐书源：https://github.com/freeok/so-novel/issues/new/choose

**Comment by freeok** [comment]
稍后发布 1.6.5-beta.1，可试用新书源 [www.shuhaige.net](https://www.shuhaige.net/)

**Comment by freeok** [comment]
最新预览版：https://github.com/freeok/so-novel/releases/tag/v1.7.0

**Comment by luozidd** [comment]
> 预览版已发布

我看还是1.6.4版本呀

**Comment by luozidd** [comment]
> 预览版已发布

看到了，可以在程序里面更新.....
