### ISSUE TITLE
V1.6.4 mac m1电脑运行报错

### ISSUE THREAD

**Issue by RoadIsLong** [freeok/so-novel#35]
版本 V1.6.4
macos 14.7.1
芯片 M1
运行报错
<img width="717" alt="image" src="https://github.com/user-attachments/assets/4efcbf8d-1e37-402d-8164-00d58e2730b9">
打包路径貌似有问题啊 目录结构对不上 Contents/Home 这两级目录丢了
<img width="999" alt="image" src="https://github.com/user-attachments/assets/3ea6c665-0715-4c0b-bdec-460e573d301b">

**Comment by RoadIsLong** [comment]
看了下 是shell脚本中的授权路径不正确 运行命令的路径是正确的 望修复
<img width="807" alt="image" src="https://github.com/user-attachments/assets/8cb05636-23e7-4354-be8c-d9c6ae780439">

**Comment by freeok** [comment]
OK👍，稍后修复

**Comment by freeok** [comment]
已修复：https://github.com/freeok/so-novel/releases/tag/v1.6.4
