### ISSUE TITLE
linux 版本更新提示GUI方面的错误

### ISSUE THREAD

**Issue by hhrensheng** [freeok/so-novel#36]
v1.62

尝试软件更新 提示
![image](https://github.com/user-attachments/assets/4d2c9a11-7f13-4ac3-993d-24bb904a5245)
（官网更新）
![image](https://github.com/user-attachments/assets/f26fd35d-c969-4587-a0f8-42cc37ac9baa)
（自动更新）
这个软件是不是不考虑服务端环境啊

**Comment by freeok** [comment]
可能linux版本导致的，下个版本修复

临时解决方法：https://www.cnblogs.com/EasonJim/p/6832657.html

或手动下载

**Comment by hhrensheng** [comment]
好的，电子书更新功能麻烦尽快上线啊，现在看的书都是连载的
