### ISSUE TITLE
不能做成自定义书源么？

### ISSUE THREAD

**Issue by Sucorde** [freeok/so-novel#37]
我这里不能使用你默认的http://www.xbiqugu.net。我打不开。

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/64152d8b-235b-49d3-ab5d-11ad09de8d06)

**Comment by freeok** [comment]
自定义书源，后面都会支持的。
Connect timed out，关闭代理或稍后再试

**Comment by Sucorde** [comment]
没开代理。

**Comment by freeok** [comment]
> 没开代理。

现在还打不开吗

**Comment by Sucorde** [comment]
现在可以了。

**Comment by Sucorde** [comment]
这个能更换地址么？

**Comment by Sucorde** [comment]
下载的文档空行太多了。能优化一下么？

**Comment by freeok** [comment]
> 这个能更换地址么？

在配置文件修改

**Comment by freeok** [comment]
> 下载的文档空行太多了。能优化一下么？

发具体，比如：书源 书名 章节名 具体的段落

**Comment by Sucorde** [comment]
http://www.xbiqugu.net  光阴之外（耳根） 所有的章节都有两个多余的空行。

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/7aa616c8-f64c-4f0b-af98-1f88b93c656f)
这里能增加一个更换源么？最好后面有提示链接用了几毫秒。

**Comment by freeok** [comment]
您的想法不错！由于该 issue 已关闭，请打开一个新的 issue 具体说明希望新增的功能
