### ISSUE TITLE
https://www.txt8080.cc/

### ISSUE THREAD

**Issue by jiang0378cen** [freeok/so-novel#39]
### 确定推荐的书源满足上述条件？

- [X] Yes

### 书源 URL

https://www.txt8080.cc/

### 书源类型

网络小说

### 勾选满足的条件（满足 3 个及以上为优质书源）

- [ ] 无限流
- [X] 书库全
- [X] 起点人气榜单的书能搜到（https://www.qidian.com/rank）
- [X] 新书热书能同步更新
- [ ] 正文错别字少

### 推荐理由

good

**Comment by freeok** [comment]
不符合条件
