### ISSUE TITLE
推荐书源 [https://69shuba.cx/index.html]

### ISSUE THREAD

**Issue by kakaluote123666** [freeok/so-novel#40]
### 确定推荐的书源满足上述条件？

- [X] Yes

### 书源 URL

https://69shuba.cx/index.html

### 书源类型

网络小说

### 勾选满足的条件（满足 3 个及以上为优质书源）

- [X] 无限流
- [X] 书库全
- [X] 起点人气榜单的书能搜到（https://www.qidian.com/rank）
- [X] 新书热书能同步更新
- [X] 正文错别字少

### 推荐理由

除了需要魔法，并且如果爬取频率过高之外容易封Ip之外。。是很好的书源

**Comment by freeok** [comment]
有五秒盾啊

**Comment by freeok** [comment]
[v1.7.3](https://github.com/freeok/so-novel/releases/tag/v1.7.3) 已支持
