### ISSUE TITLE
推荐书源 https://www.siluxs.net/

### ISSUE THREAD

**Issue by jky666doc** [freeok/so-novel#44]
### 确定推荐的书源满足上述条件？

- [X] Yes

### 书源 URL

https://www.siluxs.net/

### 书源类型

网络小说

### 勾选满足的条件（满足 4 个及以上为优质书源）

- [X] 起点人气榜单的书能搜到（https://www.qidian.com/rank）
- [ ] 正文错别字少
- [ ] 正文排版正常
- [X] 书库全
- [ ] 无限流

### 推荐理由

最新的小说比较全

**Comment by cidiry** [comment]
这个书源抓取不到章节 已经凉了

**Comment by freeok** [comment]
不符合条件：很多书只有详情，无章节、无目录，也无封面
