### ISSUE TITLE
操作逻辑问题

### ISSUE THREAD

**Issue by xiongaox** [freeok/so-novel#46]
![image](https://github.com/user-attachments/assets/d0905576-2006-4455-9f83-01cb4b7a94ea)
请问到【==> 请输入下载序号（首列的数字）】的时候，当我发现没有需要的书籍，怎么返回到上一步，重新输入其他书籍名称呢？

**Comment by xiongaox** [comment]
![image](https://github.com/user-attachments/assets/8bd65df0-f5ed-4f78-b445-f57c58aea391)
![image](https://github.com/user-attachments/assets/8ba63377-add3-4bba-b400-f2a8dea53669)
可以看到你代码新增了这个，但是我下载了最新的1.7.0为啥没有呢

**Comment by freeok** [comment]
因为 v1.7.1 还未发布😂

**Comment by freeok** [comment]
https://github.com/freeok/so-novel/releases/tag/v1.7.1
