### ISSUE TITLE
新版（1.7）搜索质量远差于旧版（1.6x）

### ISSUE THREAD

**Issue by mxxisbest** [freeok/so-novel#47]
新版（1.7）搜索排序的质量远差于旧版（1.6X），不知道什么原因造成的。
为了验证，我对比了一下1.7和1.6x的搜索，16x基本前排就是想要的，1.7不知道飞到哪里去了。
比如捞尸人，1.7直接没有纯洁龙的结果，1.6x纯洁龙的排在3位。
比如夜无疆，1.7直接没有辰东的结果，1.6x辰东的排1位。

**Comment by freeok** [comment]
书源用户可自行更换，注意配置文件。
1.7.0版本默认使用源2 https://github.com/freeok/so-novel/issues/33
