### ISSUE TITLE
下载类型为TXT，内容存在许多H5的代码，格式epub在UC中报错

### ISSUE THREAD

**Issue by wxd19891212** [freeok/so-novel#51]
下载类型为TXT，内容存在许多H5的代码，如果保存为epub格式，在UC中报错格式有问题
配置文件保持默认的书源 source-id = 2

可以把导出的TXT中的Html代码删除掉吗

eg：
<title>第一章 今日宜出行，不宜作弊</title>
  
</head>
<body>
  <h2>第一章 今日宜出行，不宜作弊</h2>
  <div>
    <p>农历二月初二，宜出行。</p><p>中雨哗啦啦的下着，落到地上，溅起泥土的芳香，落到湖面上，荡起一圈圈涟漪，落到路人的头顶，引起低声喝骂。</p><p>“谁说今天宜出行的，出门就下雨。”陆阳抱怨了一句，有些后悔没有提前带上蓑衣。</p><p>他是第一次出远门，没什么经验，雨下的突然，淋了他一身，鞋子泥泞不堪，走起路来都觉得感受到地面对自己的恶意——他需要把脚从泥坑里拔出来。</p><p>哒哒哒的声音从身后传来，引起陆阳的注意。</p><p>陆阳扭头看去，发现是一辆马车靠近自己，马车上并无马夫，老马仿佛认路，不需要谁人来驾驭它。</p><p>“好神异的马。”陆阳赞叹，老马额头上有几枚鳞片，仿佛蛇鳞，显然是某种异种妖兽。</p><p>他虽不懂个中价值，但也知道这匹老马的珍贵。</p><p>最起码以他的财力是买不起的。</p><p>“这位兄台雨中漫步，当真是好雅兴，不妨来车中一坐？”</p><p>马车内传来男子爽朗的笑声，陆阳接受了男子的好意，把脚从泥坑里拔出来，急忙上车。</p><p>“叨扰了，在下陆阳。”陆阳小心翼翼的坐进车里，害怕身上的雨水和泥土弄脏了马车。</p><p>“孟景舟。”马车的主人和他的声音一样，是个大大咧咧的青年，乐观爽朗，仿佛和谁都能说上两句。</p><p>“陆兄也是来参加问道宗选拔的？”</p><p>“碰碰运气而已。”</p><p>孟景舟哈哈大笑：“陆兄，诚实一些又何妨，若你真的只是想碰碰运气，便不会在雨中漫步前往问道宗了。”</p><p>陆阳有些羞愧：“谁不想进入问道宗。”</p><p>问道宗，位列中央大陆五大仙门之一，修仙大能不计其数，强盛至极，今日问道宗招收弟子，不知有多少人想来试上一试。</p><p>陆阳和孟景舟便是其中之二。</p><p>陆阳穿越到中央大陆，父母死的早，是靠着父母留下的一点遗产，以及邻里的救济才活下来的。</p><p>在小镇生活的十几年里，他听说书先生讲有仙人剑叩天门，听说过五百里外河妖翻身，洪水泛滥，听说过仙门弟子飞剑斩妖，除魔卫道，见过邋遢道士坑蒙拐骗，凌空而起，当众越狱，又被凌空而起的官家抓了回来。</p><p>那时候他便知道，这里非他所熟悉的世界，非他熟悉的任何一个朝代，这里是个人伟力集于一身的修仙世界。</p><p>他想求仙问道，学习长生仙法。</p><p>问道宗便是他选择的第一站。</p><p>选择问道宗没有别的原因，单纯是他家周围没有其他宗门，只有问道宗一家。</p><p>问道宗在这里，其他宗门不会自讨没趣，选择在附近开宗立派。</p><p>在交谈中陆阳得知孟景舟出自修仙世家，对于修仙的知识的掌握要远比陆阳要多。</p><p>“问道宗招收弟子的要求是十六岁以下的凡人，不止是问道宗，大多数宗门都是这般要求。”</p><p>“修仙一途道阻且长，练气、筑基、金丹、元婴、化神、炼虚、合体、渡劫，每个境界都是一道分水岭，不知卡住多少人，十进一，二十进一，乃至一百个里面才出现一个。”</p><p>“决定修仙成就的因素有很多，例如运气、智慧、灵根……对了陆兄，你知道自己是什么灵根吗？”</p><p>“问道宗虽说对灵根要求不高，但太差的灵根也是不要的。”</p><p>陆阳皱眉，他对灵根这个词还是从说书先生那里知道的，并不知道自己是什么灵根。</p><p>“不知道，孟兄你呢？”</p><p>孟景舟面色变得十分困惑，同样摇头：“我曾在族中测试过灵根，但族老面带愁容，并不告诉我结果，只是说我的天赋惊为天人，拜入五大仙门不成问题，等日后拜在五大仙门时自会知道，我私下里偷偷问父母，他们比族老更加忧愁，同样不告诉我。”</p><p>陆阳推测道：“有可能是你的灵根过于惊世骇俗，容易给孟家带来灾祸，只有问道宗这种庞然大物才能保住你。”</p><p>“跟我猜的一样。”孟景舟拍着陆阳的肩膀，一副遇到知己的样子，越看陆阳越觉得此人和自己一样才华横溢，是天生的修道种子。</p><p>陆阳听着外面越来越大的雨声，庆幸孟景舟让自己上车。</p><p>“停下。”孟景舟突然喊了一嗓子，老马吧嗒吧嗒走了几步，慢慢停下。</p><p>马车算是一件异宝，孟景舟可以看到马车外的情况。</p><p>孟景舟看到马车外面有一名女子走在雨中，跟刚才的陆阳一样。</p><p>“这位姐姐走在这个方向，想必也是要去问道宗参加考验，雨下的这般大，不如来车上歇歇脚？”</p><p>女子有些惊讶孟景舟的提议，想了想，也便同意了。</p><p>女子一上车，孟景舟和陆阳便齐齐愣住了。</p><p>孟景舟自付是见过世面的，但还从未见过这般漂亮的女子，陆阳就更不用提，他见过最漂亮的女子是隔壁卖豆腐的小寡妇。</p><p>当然，陆阳是正人君子，对小寡妇没有任何非分之想。</p><p>女子如同一朵妖而不艳的莲花，一袭白衣，亭亭玉立，明眸皓齿，给人一种恍如隔世的感觉。</p><p>女子右手腕还带着一串用金色铃铛。</p><p>“云芝谢过两位了。”</p><p>女子声音宛如清泉，让人听着很舒服。</p><p>陆阳发现了异样，小声说道：“孟兄，她怎么身上是干的，会不会是妖怪？”</p><p>说书故事里可是经常有妖怪化作美女，引诱他们这种年轻力壮的小伙子。</p><p>刚才陆阳浇的跟落汤鸡一样，狼狈不堪，反观云芝，身上没有半点雨水，全然不像是在雨中走过的样子。</p><p>孟景舟没有多想：“也许是身上带有能够避雨的异宝，这在世家里也算常见。”</p><p>孟景舟不担心云芝是妖魔鬼怪魑魅魍魉，这里是问道宗的地盘，哪家妖怪不要命了，敢来问道宗闹事。</p><p>“云芝姑娘可是来参加问道宗测试的？”</p><p>“正是。”</p><p>孟景舟殷勤的说道：“我这里正好有问道宗的考验内容，是花重金从问道宗长老那里买的，云芝姑娘要不要听听？”</p><p>陆阳诧异的看着孟景舟，你怎么没跟我说过？</p><p>云芝比陆阳还要诧异：“这可是作弊，万一被问道宗发现了……”</p><p>孟景舟摆手，一脸自信：“我这辆马车乃是异宝，就算是那些修仙大能、隐居不出的老怪物，也无法用神识探查到这里。”</p><p>“原来如此，还请孟公子告知考验内容。”</p><p>陆阳闻言，也竖起耳朵聆听。</p><p>孟景舟清了清嗓子：“问道宗测试一共分为三关，第一关测试灵根，这是硬性测试，没有取巧和走捷径的可能，有操作空间的是第二关和第三关。”</p><p>“第二关考验的是品行，一架马车失控，要撞向躺在路边的五个人，撞倒必死无疑，还有一个人躺在不远处，我们作为局外人可以控制马车失控的方向，是选择不去理睬，撞死五个人，还是改变方向，撞死另外一个人？”</p><p>陆阳不假思索：“撞死另外一个人。”</p><p>孟景舟十分诧异，自从他得知第二关内容后一直没有想到解决办法，怎么陆阳立即就能做出了决定？</p><p>选择不理睬，就要眼睁睁的看着五个人被撞死，道理上过得去心里也过意不去。</p><p>选择改变方向，撞死另外一人，那这个人就这么倒霉，活该被撞死，而且还是自己动的手。</p><p>孟景舟将自己的疑问讲出，陆阳解释道：“哪有这么多时间让伱思考，等你思考出结果，那五个人早就撞死了。我猜问道宗考验的不是你选择救五个人还是一个人，而是看你能不能迅速做出决定。”</p><p>“我听说书先生讲，修士斗法差之一毫便是生死，第二关考验的品行是什么，是看你优柔寡断还是决策果断，最短的时间作出决定才是最重要的。”</p><p>孟景舟恍然大悟。</p><p>“第三关考验的是诚实，问道宗有一面镜子，可以判断你说的是真话还是假话，若是被发现说了假话，直接踢出考验。”</p><p>陆阳思索道：“这一关倒是简单，如果没有提前提醒，很容易说假话掩盖自己，不过既然提前知道了，说真话就好。”</p><p>孟景舟点头，他也是这么想的。</p><p>两人商量了一会，提出不少可能出现的意外和对策，合计一番觉得天衣无缝。</p><p>云芝姑娘露出一丝笑意，似是觉得两人说的是好办法。</p><p>“多谢陆少侠相告。”</p><p>“嗯，雨停了？”陆阳发现车外没有再传来滴滴答答雨水落地的声音，不免好奇向外探去。</p><p>刚刚走过的地方依旧下着瓢泼大雨，而他们所在的地方阳光明媚，鸟语花香，就好像有一道绝世剑气将世界分割为阴阳两半，永无交集。</p><p>陆阳抬头，只见无数奇珍异兽、仙家法宝赶往那直通天际的巍峨山岳。</p><p>巍峨的山岳被阳光镀上一层淡金，瑰丽的花纹自山岳之后蔓延而出，铺天盖地，挡住了大雨。</p><p>那是问道宗的门户山岳，其上是护宗大阵，无人可破。</p><p>出于对问道宗的尊敬，修道天才在自家长辈的带领下，降落在山脚下，等待问道宗开启考验。</p><p>老马已经是颇为罕见的异种妖兽了，但和山脚下那些停歇的神俊异兽相比，还是差上一些。</p><p>“妈诶，这可比我们孟家的宅子霸气多了。”孟景舟搓手，有些紧张，想到自己马上就能通过考验，成为问道宗一员，心中更多的还是激动。</p><p>陆阳不言，他在家的时候能看到这座山岳，那时候距离太远，没什么感觉，站在山脚下，这才意识到这是何等庞然大物。</p><p>他有些紧张，第二三关都有办法，可他到现在也不知道自己的灵根是什么，说不定连第一道考验都过不去。</p><p>几十名修士凌空而立，守在山岳前，皆散发着强大气息波动，陆阳怀疑他们若是完全放开气息，在场怕是连能站着的都没有几个。</p><p>这些修士沉默不言，没来由的给人心理压力。</p><p>陆阳听到有家族长辈给后辈介绍：“看道袍制式，这是问道宗的核心弟子，皆拜师在各大长老门下，以后这些人就是你的师兄弟。”</p><p>“你不用紧张，他们并非刻意给你压力，看样子他们是在等主持这场考验的人，等主持者到了，考验就该开始了。”</p><p>陆阳扭头，想看看云芝姑娘的反应，是激动还是紧张。</p><p>总不能还是一脸淡然吧？</p><p>“云芝姑娘你……”</p><p>陆阳刚想说什么，就见云芝姑娘轻迈脚步，每步落下之前，便会有一朵白莲托起她柔弱的身躯。</p><p>众人哗然，家族长辈额头露出冷汗，连忙让后辈噤声。</p><p>白莲铺设成路，横跨众人，云芝姑娘来到问道宗核心弟子中间，问道宗弟子对其躬身一拜，以示尊敬，云芝姑娘轻抬素手而后，面向众人，抿嘴微笑。</p><p>“让大家久等了，我是问道宗大师姐，本次考验主持者。”</p><p>“我宣布，考验正式开始。”</p><p>说罢，云芝姑娘还是似笑非笑的撇了一眼呆滞的陆阳和孟景舟。</p><p>她确实是来参加问道宗考验的，只不过她不是考生，而是考官。</p>
  </div>
</body>
</html>
![e1329ed57cca0927257acacfd5d7f01](https://github.com/user-attachments/assets/97a2344e-9d45-497b-a3e5-34103b31fdc1)

**Comment by wxd19891212** [comment]
`  <title>第一章 今日宜出行，不宜作弊</title>
  
</head>
<body>
  <h2>第一章 今日宜出行，不宜作弊</h2>
  <div>
    <p>农历二月初二，宜出行。</p><p>中雨哗啦啦的下着，落到地上，溅起泥土的芳香，落到湖面上，荡起一圈圈涟漪，落到路人的头顶，引起低声喝骂。</p><p>“谁说今天宜出行的，出门就下雨。”陆阳抱怨了一句，有些后悔没有提前带上蓑衣。</p><p>他是第一次出远门，没什么经验，雨下的突然，淋了他一身，鞋子泥泞不堪，走起路来都觉得感受到地面对自己的恶意——他需要把脚从泥坑里拔出来。</p><p>哒哒哒的声音从身后传来，引起陆阳的注意。</p><p>陆阳扭头看去，发现是一辆马车靠近自己，马车上并无马夫，老马仿佛认路，不需要谁人来驾驭它。</p><p>“好神异的马。”陆阳赞叹，老马额头上有几枚鳞片，仿佛蛇鳞，显然是某种异种妖兽。</p><p>他虽不懂个中价值，但也知道这匹老马的珍贵。</p><p>最起码以他的财力是买不起的。</p><p>“这位兄台雨中漫步，当真是好雅兴，不妨来车中一坐？”</p><p>马车内传来男子爽朗的笑声，陆阳接受了男子的好意，把脚从泥坑里拔出来，急忙上车。</p><p>“叨扰了，在下陆阳。”陆阳小心翼翼的坐进车里，害怕身上的雨水和泥土弄脏了马车。</p><p>“孟景舟。”马车的主人和他的声音一样，是个大大咧咧的青年，乐观爽朗，仿佛和谁都能说上两句。</p><p>“陆兄也是来参加问道宗选拔的？”</p><p>“碰碰运气而已。”</p><p>孟景舟哈哈大笑：“陆兄，诚实一些又何妨，若你真的只是想碰碰运气，便不会在雨中漫步前往问道宗了。”</p><p>陆阳有些羞愧：“谁不想进入问道宗。”</p><p>问道宗，位列中央大陆五大仙门之一，修仙大能不计其数，强盛至极，今日问道宗招收弟子，不知有多少人想来试上一试。</p><p>陆阳和孟景舟便是其中之二。</p><p>陆阳穿越到中央大陆，父母死的早，是靠着父母留下的一点遗产，以及邻里的救济才活下来的。</p><p>在小镇生活的十几年里，他听说书先生讲有仙人剑叩天门，听说过五百里外河妖翻身，洪水泛滥，听说过仙门弟子飞剑斩妖，除魔卫道，见过邋遢道士坑蒙拐骗，凌空而起，当众越狱，又被凌空而起的官家抓了回来。</p><p>那时候他便知道，这里非他所熟悉的世界，非他熟悉的任何一个朝代，这里是个人伟力集于一身的修仙世界。</p><p>他想求仙问道，学习长生仙法。</p><p>问道宗便是他选择的第一站。</p><p>选择问道宗没有别的原因，单纯是他家周围没有其他宗门，只有问道宗一家。</p><p>问道宗在这里，其他宗门不会自讨没趣，选择在附近开宗立派。</p><p>在交谈中陆阳得知孟景舟出自修仙世家，对于修仙的知识的掌握要远比陆阳要多。</p><p>“问道宗招收弟子的要求是十六岁以下的凡人，不止是问道宗，大多数宗门都是这般要求。”</p><p>“修仙一途道阻且长，练气、筑基、金丹、元婴、化神、炼虚、合体、渡劫，每个境界都是一道分水岭，不知卡住多少人，十进一，二十进一，乃至一百个里面才出现一个。”</p><p>“决定修仙成就的因素有很多，例如运气、智慧、灵根……对了陆兄，你知道自己是什么灵根吗？”</p><p>“问道宗虽说对灵根要求不高，但太差的灵根也是不要的。”</p><p>陆阳皱眉，他对灵根这个词还是从说书先生那里知道的，并不知道自己是什么灵根。</p><p>“不知道，孟兄你呢？”</p><p>孟景舟面色变得十分困惑，同样摇头：“我曾在族中测试过灵根，但族老面带愁容，并不告诉我结果，只是说我的天赋惊为天人，拜入五大仙门不成问题，等日后拜在五大仙门时自会知道，我私下里偷偷问父母，他们比族老更加忧愁，同样不告诉我。”</p><p>陆阳推测道：“有可能是你的灵根过于惊世骇俗，容易给孟家带来灾祸，只有问道宗这种庞然大物才能保住你。”</p><p>“跟我猜的一样。”孟景舟拍着陆阳的肩膀，一副遇到知己的样子，越看陆阳越觉得此人和自己一样才华横溢，是天生的修道种子。</p><p>陆阳听着外面越来越大的雨声，庆幸孟景舟让自己上车。</p><p>“停下。”孟景舟突然喊了一嗓子，老马吧嗒吧嗒走了几步，慢慢停下。</p><p>马车算是一件异宝，孟景舟可以看到马车外的情况。</p><p>孟景舟看到马车外面有一名女子走在雨中，跟刚才的陆阳一样。</p><p>“这位姐姐走在这个方向，想必也是要去问道宗参加考验，雨下的这般大，不如来车上歇歇脚？”</p><p>女子有些惊讶孟景舟的提议，想了想，也便同意了。</p><p>女子一上车，孟景舟和陆阳便齐齐愣住了。</p><p>孟景舟自付是见过世面的，但还从未见过这般漂亮的女子，陆阳就更不用提，他见过最漂亮的女子是隔壁卖豆腐的小寡妇。</p><p>当然，陆阳是正人君子，对小寡妇没有任何非分之想。</p><p>女子如同一朵妖而不艳的莲花，一袭白衣，亭亭玉立，明眸皓齿，给人一种恍如隔世的感觉。</p><p>女子右手腕还带着一串用金色铃铛。</p><p>“云芝谢过两位了。”</p><p>女子声音宛如清泉，让人听着很舒服。</p><p>陆阳发现了异样，小声说道：“孟兄，她怎么身上是干的，会不会是妖怪？”</p><p>说书故事里可是经常有妖怪化作美女，引诱他们这种年轻力壮的小伙子。</p><p>刚才陆阳浇的跟落汤鸡一样，狼狈不堪，反观云芝，身上没有半点雨水，全然不像是在雨中走过的样子。</p><p>孟景舟没有多想：“也许是身上带有能够避雨的异宝，这在世家里也算常见。”</p><p>孟景舟不担心云芝是妖魔鬼怪魑魅魍魉，这里是问道宗的地盘，哪家妖怪不要命了，敢来问道宗闹事。</p><p>“云芝姑娘可是来参加问道宗测试的？”</p><p>“正是。”</p><p>孟景舟殷勤的说道：“我这里正好有问道宗的考验内容，是花重金从问道宗长老那里买的，云芝姑娘要不要听听？”</p><p>陆阳诧异的看着孟景舟，你怎么没跟我说过？</p><p>云芝比陆阳还要诧异：“这可是作弊，万一被问道宗发现了……”</p><p>孟景舟摆手，一脸自信：“我这辆马车乃是异宝，就算是那些修仙大能、隐居不出的老怪物，也无法用神识探查到这里。”</p><p>“原来如此，还请孟公子告知考验内容。”</p><p>陆阳闻言，也竖起耳朵聆听。</p><p>孟景舟清了清嗓子：“问道宗测试一共分为三关，第一关测试灵根，这是硬性测试，没有取巧和走捷径的可能，有操作空间的是第二关和第三关。”</p><p>“第二关考验的是品行，一架马车失控，要撞向躺在路边的五个人，撞倒必死无疑，还有一个人躺在不远处，我们作为局外人可以控制马车失控的方向，是选择不去理睬，撞死五个人，还是改变方向，撞死另外一个人？”</p><p>陆阳不假思索：“撞死另外一个人。”</p><p>孟景舟十分诧异，自从他得知第二关内容后一直没有想到解决办法，怎么陆阳立即就能做出了决定？</p><p>选择不理睬，就要眼睁睁的看着五个人被撞死，道理上过得去心里也过意不去。</p><p>选择改变方向，撞死另外一人，那这个人就这么倒霉，活该被撞死，而且还是自己动的手。</p><p>孟景舟将自己的疑问讲出，陆阳解释道：“哪有这么多时间让伱思考，等你思考出结果，那五个人早就撞死了。我猜问道宗考验的不是你选择救五个人还是一个人，而是看你能不能迅速做出决定。”</p><p>“我听说书先生讲，修士斗法差之一毫便是生死，第二关考验的品行是什么，是看你优柔寡断还是决策果断，最短的时间作出决定才是最重要的。”</p><p>孟景舟恍然大悟。</p><p>“第三关考验的是诚实，问道宗有一面镜子，可以判断你说的是真话还是假话，若是被发现说了假话，直接踢出考验。”</p><p>陆阳思索道：“这一关倒是简单，如果没有提前提醒，很容易说假话掩盖自己，不过既然提前知道了，说真话就好。”</p><p>孟景舟点头，他也是这么想的。</p><p>两人商量了一会，提出不少可能出现的意外和对策，合计一番觉得天衣无缝。</p><p>云芝姑娘露出一丝笑意，似是觉得两人说的是好办法。</p><p>“多谢陆少侠相告。”</p><p>“嗯，雨停了？”陆阳发现车外没有再传来滴滴答答雨水落地的声音，不免好奇向外探去。</p><p>刚刚走过的地方依旧下着瓢泼大雨，而他们所在的地方阳光明媚，鸟语花香，就好像有一道绝世剑气将世界分割为阴阳两半，永无交集。</p><p>陆阳抬头，只见无数奇珍异兽、仙家法宝赶往那直通天际的巍峨山岳。</p><p>巍峨的山岳被阳光镀上一层淡金，瑰丽的花纹自山岳之后蔓延而出，铺天盖地，挡住了大雨。</p><p>那是问道宗的门户山岳，其上是护宗大阵，无人可破。</p><p>出于对问道宗的尊敬，修道天才在自家长辈的带领下，降落在山脚下，等待问道宗开启考验。</p><p>老马已经是颇为罕见的异种妖兽了，但和山脚下那些停歇的神俊异兽相比，还是差上一些。</p><p>“妈诶，这可比我们孟家的宅子霸气多了。”孟景舟搓手，有些紧张，想到自己马上就能通过考验，成为问道宗一员，心中更多的还是激动。</p><p>陆阳不言，他在家的时候能看到这座山岳，那时候距离太远，没什么感觉，站在山脚下，这才意识到这是何等庞然大物。</p><p>他有些紧张，第二三关都有办法，可他到现在也不知道自己的灵根是什么，说不定连第一道考验都过不去。</p><p>几十名修士凌空而立，守在山岳前，皆散发着强大气息波动，陆阳怀疑他们若是完全放开气息，在场怕是连能站着的都没有几个。</p><p>这些修士沉默不言，没来由的给人心理压力。</p><p>陆阳听到有家族长辈给后辈介绍：“看道袍制式，这是问道宗的核心弟子，皆拜师在各大长老门下，以后这些人就是你的师兄弟。”</p><p>“你不用紧张，他们并非刻意给你压力，看样子他们是在等主持这场考验的人，等主持者到了，考验就该开始了。”</p><p>陆阳扭头，想看看云芝姑娘的反应，是激动还是紧张。</p><p>总不能还是一脸淡然吧？</p><p>“云芝姑娘你……”</p><p>陆阳刚想说什么，就见云芝姑娘轻迈脚步，每步落下之前，便会有一朵白莲托起她柔弱的身躯。</p><p>众人哗然，家族长辈额头露出冷汗，连忙让后辈噤声。</p><p>白莲铺设成路，横跨众人，云芝姑娘来到问道宗核心弟子中间，问道宗弟子对其躬身一拜，以示尊敬，云芝姑娘轻抬素手而后，面向众人，抿嘴微笑。</p><p>“让大家久等了，我是问道宗大师姐，本次考验主持者。”</p><p>“我宣布，考验正式开始。”</p><p>说罢，云芝姑娘还是似笑非笑的撇了一眼呆滞的陆阳和孟景舟。</p><p>她确实是来参加问道宗考验的，只不过她不是考生，而是考官。</p>
  </div>
</body>
</html>`

**Comment by wxd19891212** [comment]
这里发html代码他直接识别了，显示不出来

**Comment by freeok** [comment]
你好，请提供下版本号和书源 ID

**Comment by freeok** [comment]
从图片看，设备是 IOS，epub 格式建议使用自带的图书 APP

**Comment by freeok** [comment]
下载格式为 txt，是不可能出现 html 的。从图片来看，你应该是直接修改了扩展名，将 epub 改为了 txt，这样是错误的

正确的 txt 内容

![image](https://github.com/user-attachments/assets/6d207793-b522-4a64-bc2b-c45ec0ac0481)

下载 txt 的正确方法

![image](https://github.com/user-attachments/assets/44fcf8d4-dfaa-469e-9648-d2ecf6d43dcd)
