### ISSUE TITLE
关于WPS无法正确打开的修复参考

### ISSUE THREAD

**Issue by Cillo-x** [freeok/so-novel#54]
关于WPS无法打开 README 给出的方法是下载 TXT 模式，我认为原因是格式不正确，而且可以很简单地修复

用 Sigil【一个EPUB电子书制作工具】打开下载好的电子书文件，可以看到如下提示
![图片](https://github.com/user-attachments/assets/91a2ab8f-c451-496a-810f-afc26a93f1c4)
可以看到 Sigil 帮我把电子书修复了，修复好了的epub 就可以被WPS打开了

经过我的对比，只是在每一个HTML 文件开头添加了 DOCTYPE 等字样
![图片](https://github.com/user-attachments/assets/40bd6bbd-1e29-46e1-a0c3-06ef9b93b545)

参考维基百科 https://zh.wikipedia.org/wiki/EPUB#%E5%BC%80%E6%94%BE%E5%87%BA%E7%89%88%E7%BB%93%E6%9E%842.0.1
相关条目，应该是需要添加这些字符的

供作者参考，期待修复

**Comment by freeok** [comment]
https://github.com/freeok/so-novel/issues/32、https://github.com/freeok/so-novel/issues/38
当时我就排查了下，目前可以确定是 wps 的问题，稍后具体解释下原因，感谢你提供的思路

**Comment by freeok** [comment]
EPUB 本质上是一个结构固定的 ZIP 文件，解压后在 OEBPS 文件夹下可以找到一个名为 content.opf 的文件，这是 EPUB 的核心文件，包含了书籍的元数据、章节引用、目录引用等。很多 EPUB 文件损坏的问题，往往与 content.opf 有关。项目中使用了 epublib 来生成符合 W3C 标准的 EPUB 文件，生成的 content.opf 文件采用了命名空间的写法，这是更为标准的做法。自 EPUB 2（2007年）发布以来，就已支持命名空间前缀，推荐使用前缀形式，因为它在兼容性和可读性方面更优，特别是在老旧的 EPUB 2.0 阅读器中。

![image](https://github.com/user-attachments/assets/1fe11d36-d944-45e7-a4a5-0ff5158272a1)

然而，WPS 的解析器不支持命名空间前缀，因此无法正确解析包含命名空间的 EPUB 文件。当使用 Sigil 打开 EPUB 时，Sigil 会自动去除 content.opf 中所有标签的 opf: 前缀（这可能是出于兼容性考虑）。此外，Sigil 在处理 EPUB 时，会为 HTML 文件添加 XHTML 1.1 的声明，我进行过测试，发现这一声明是否存在并不影响 EPUB 文件的正常打开。在选择使用 epublib 时，我也通过 [epubcheck](https://github.com/w3c/epubcheck) 对生成的文件进行了标准检验，结果显示，除了部分章节中（如“正在手打中”页面）包含未闭合的 <br> 标签等元素，导致出现 fatal 和 error，其他部分均无问题。Sigil 在打开 WPS 无法识别的 EPUB 时，弹出的警告也正是由于这个原因。

![image](https://github.com/user-attachments/assets/b9524fde-a3de-4734-80fe-288098306a84)

以 so-novel 生成的《绍宋.epub》为例，当前已知能够正常打开的阅读器包括：Apple Books、Moon+ Reader、Koodo Reader 和 Kindle。WPS 对 EPUB 的支持并不完全，它本质上是办公软件，而非专门的电子书阅读器。

提供一些解决方案：

1. 使用专业的电子书阅读器打开 EPUB 文件。
2. 若仍需使用 WPS，建议手动“修复”文件。
3. 强行“修复”，通过增加一个兼容 WPS 的配置项。

若有错误或改进意见，还望指正和交流。

**Comment by Cillo-x** [comment]
感谢作者用心回复，原来如此，是我没有认真研究就下结论了
