### ISSUE TITLE
推荐书源 <https://m.czqiumao.com/>

### ISSUE THREAD

**Issue by 2784585422** [freeok/so-novel#60]
### 确定推荐的书源满足上述条件？

- [X] Yes

### 书源 URL

https://m.czqiumao.com/

### 书源类型

网络小说

### 勾选满足的条件，不确定的不勾选

- [ ] 起点月票榜的书能搜到：https://www.qidian.com/rank/yuepiao/
- [ ] 起点收藏榜的书能搜到：https://www.qidian.com/rank/collect/
- [X] 能搜到知名小说（无论平台、是否连载）
- [X] 正文内容纯净（没有与文章无关的内容）
- [X] 正文错别字少
- [X] 正文排版正常
- [ ] 无反爬机制

### 推荐理由

书全,无错乱

**Comment by freeok** [comment]
搜索需要验证码
