### ISSUE TITLE
推荐书源 <https://69shuba.cx/index.html>

### ISSUE THREAD

**Issue by 1259601878** [freeok/so-novel#61]
### 确定推荐的书源满足上述条件？

- [X] Yes

### 书源 URL

https://69shuba.cx/index.html

### 书源类型

网络小说

### 勾选满足的条件，不确定的不勾选

- [X] 起点月票榜的书能搜到：https://www.qidian.com/rank/yuepiao/
- [X] 起点收藏榜的书能搜到：https://www.qidian.com/rank/collect/
- [X] 能搜到知名小说（无论平台、是否连载）
- [X] 正文内容纯净（没有与文章无关的内容）
- [X] 正文错别字少
- [X] 正文排版正常
- [X] 无反爬机制

### 推荐理由

起点防盗章节都是正常的

**Comment by freeok** [comment]
不符合要求 https://github.com/freeok/so-novel/issues/40

**Comment by freeok** [comment]
[v1.7.3](https://github.com/freeok/so-novel/releases/tag/v1.7.3) 已支持
