### ISSUE TITLE
【Bug】搜索结果第1~2由于行数限制被删除

### ISSUE THREAD

**Issue by Lucriobus-Forint** [freeok/so-novel#67]
### 先决条件

- [X] 我已下载最新版本测试，问题依然存在
- [X] 我已查阅 [使用说明](https://github.com/freeok/so-novel/blob/main/input/readme.txt) 以及 [常见问题](https://github.com/freeok/so-novel?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
- [X] 我已确保 [已有的问题](./?q=is%3Aissue) 中无类似 issue，否则请在已有的 issue 内进行讨论
- [X] 我已关闭所有杀毒软件/代理软件后测试，问题依然存在
- [X] 我已填写一个简洁明了的标题，以便他人快速检索

### 操作系统名称

Windows

### 操作系统版本

win7

### so-novel 版本

v1.7.2

### 问题描述

命令提示符的显示行数有限，一次出100个结果有时会导致第一第二个被清除

建议减少搜索结果数，或者分页

### 复现步骤

1.运行程序

2.选择功能[下载小说]

3.搜索，例子：剑来

4.出现情况

**Comment by freeok** [comment]
需要提供截图、书源 ID

**Comment by freeok** [comment]
cmd 设置问题，见 https://blog.csdn.net/litong131219/article/details/102991374
